### ISSUE TITLE
Allow connecting to an existing node

### ISSUE THREAD

**Issue by caike** [easy1staking-com/liqwid-finance-liquidation-bot#1]
Allow leveraging an existing Cardano node instance instead of starting a new one.

**Comment by nemo83** [comment]
Hey!! Thanks for opening the first issue!

So I quickly put this compose together.

https://github.com/easy1staking-com/liqwid-finance-liquidation-bot/blob/main/docker-compose-no-node.yaml

You will need to provide `CARDANO_NODE_SOCKET_PATH` env var when issuing the docker compose up.

The `CARDANO_NODE_SOCKET_PATH` must point to the folder where the `node.socket` is created.

Also bear in mind that during node startup, the `node.socket` is not present.

Give it a go, and let me know it works for you and how you get on w/ it.

**Comment by nemo83** [comment]
Thanks for the contribution, will close this one now.
